import { SatellitePass } from "@/services/celestrak/passPredictionService";

function icsDate(d: Date): string {
  return d.toISOString().replace(/[-:]/g, "").split(".")[0] + "Z";
}

function cardinalShort(az: number): string {
  const dirs = ["N", "NNE", "NE", "ENE", "E", "ESE", "SE", "SSE", "S", "SSW", "SW", "WSW", "W", "WNW", "NW", "NNW", "N"];
  return dirs[Math.round(az / 22.5)] ?? "N";
}

/** Builds an RFC-5545 .ics file for a single satellite pass and triggers a
 * browser download. No backend or library needed — passes are short, simple
 * single-VEVENT calendars. */
export function downloadPassIcs(pass: SatellitePass, locationLabel: string) {
  const uid = `${pass.satId}-${pass.riseTime.getTime()}@zenith-observatory`;
  const summary = `${pass.satName} pass — ${pass.maxElevationDeg.toFixed(0)}° max elevation`;
  const description = [
    `Rise: ${cardinalShort(pass.riseAzimuthDeg)} horizon`,
    `Max elevation: ${pass.maxElevationDeg.toFixed(0)}° at ${pass.maxTime.toLocaleTimeString()}`,
    `Set: ${cardinalShort(pass.setAzimuthDeg)} horizon`,
    `Duration: ${pass.durationSec}s`,
    pass.isVisible ? "Naked-eye visible (observer dark, satellite sunlit)." : "Not naked-eye visible (daylight pass).",
    `Observed from: ${locationLabel}`,
    "Generated by Zenith Observatory",
  ].join("\\n");

  const ics = [
    "BEGIN:VCALENDAR",
    "VERSION:2.0",
    "PRODID:-//Zenith Observatory//Pass Predictor//EN",
    "BEGIN:VEVENT",
    `UID:${uid}`,
    `DTSTAMP:${icsDate(new Date())}`,
    `DTSTART:${icsDate(pass.riseTime)}`,
    `DTEND:${icsDate(pass.setTime)}`,
    `SUMMARY:${summary}`,
    `DESCRIPTION:${description}`,
    `LOCATION:${locationLabel}`,
    "BEGIN:VALARM",
    "TRIGGER:-PT10M",
    "ACTION:DISPLAY",
    "DESCRIPTION:Satellite pass starting in 10 minutes",
    "END:VALARM",
    "END:VEVENT",
    "END:VCALENDAR",
  ].join("\r\n");

  const blob = new Blob([ics], { type: "text/calendar;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `${pass.satName.replace(/\s+/g, "-").toLowerCase()}-pass-${pass.riseTime.toISOString().slice(0, 10)}.ics`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
